spring.application.name=bookstore-backend
server.port=8811

# MySQL Configuration (matching docker-compose.yml)
spring.datasource.url=jdbc:mysql://localhost:3306/bookstore?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=user
spring.datasource.password=password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA and Hibernate
# Keep it on "none" since we're using schema.sql and data.sql for structure
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Initialization Configuration
# This ensures that schema.sql and then data.sql are executed on startup
spring.sql.init.mode=always
